### ISSUE TITLE
CNCF Incubating Onboarding Todo List

### ISSUE THREAD

**Issue by greenie-msft** [dapr/community#107]
- [x] Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction - @msfussell 
- [x]  Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/ - @msfussell 
- [ ]  Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy - @artursouza @msfussell 
- [ ]  Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md - @msfussell 
- [x]  Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/ - @greenie-msft  
 - [x] Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist - @artursouza 
- [x]  Has your project adopted open governance already? see http://opengovernance.dev - @msfussell 
- [x]  Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details) - Discord instead of Slack
 - [x] Is your project in its own separate neutral github organization? - - @msfussell 
- [x]  Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io - @willtsai
- [x]  Create maintainer list + add to aggregated https://maintainers.cncf.io list by submitting a PR to it - @msfussell 
- [x]  Have added your project to https://github.com/cncf/contribute - @willtsai 
- [x]  Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork - @greenie-msft 

Things that CNCF will need from the project:
- [x]  Provide emails for the maintainers added to https://maintainers.cncf.io in order to get access to the maintainers mailing list and ServiceDesk - @msfussell 
- [ ]  Domain: transfer domain to the CNCF - please send a transfer code to project-onboarding@cncf.io - @greenie-msft 
- [ ]  Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements - @greenie-msft 
- [x]  GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership - @yaron2 
- [ ]  GitHub: ensure DCO or CLA are enabled for all GitHub repositories of the project - @artursouza 
- [x]  Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed - @AaronCrawfis 
- [x]  Website: Analytics transferred to amye@linuxfoundation.org - @AaronCrawfis 
- [x]  CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en - @artursouza 

Things that the CNCF will do or help the project to do:

- [x]  Devstats: add to devstats https://devstats.cncf.io/
- [x]  Marketing: update relevant intro + slide decks
- [x]  Events: update CFP + Registration + CFP Area forms
- [ ]  ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
- [x]  CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [ ]  Create space for meetings/events on https://community.cncf.io, e.g., https://community.cncf.io/pravega-community/ - (https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects)
- [ ]  Adopt a license scanning tool, like FOSSA or Snyk

**Comment by AaronCrawfis** [comment]
Google analytics data has been shared and website footer is in review: https://github.com/dapr/website/pull/55

**Comment by msfussell** [comment]
If you do any update here, please also leave a comment in the CNCF issue here https://github.com/cncf/toc/issues/738 which is the official check off list.

**Comment by greenie-msft** [comment]
@willtsai regarding this task:

Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io - @willtsai

I think "sandbox" is a mistake and should instead be added to the "incubating" projects.

**Comment by yaron2** [comment]
> @willtsai regarding this task:
> 
> Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io - @willtsai
> 
> I think "sandbox" is a mistake and should instead be added to the "incubating" projects.

I can already see Dapr as Incubating under the Serverless/Framework sections.

**Comment by msfussell** [comment]
For this issue
 Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
@artursouza or someone please do this https://github.com/dapr/dapr/issues/3911
@orizohar - Could you do this https://github.com/dapr/docs/issues/1963

**Comment by willtsai** [comment]
> > @willtsai regarding this task:
> > Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io - @willtsai
> > I think "sandbox" is a mistake and should instead be added to the "incubating" projects.
> 
> I can already see Dapr as Incubating under the Serverless/Framework sections.

yes, looks like this was already done as a part of https://github.com/cncf/landscape/pull/2346. I will check off the task and add a comment in the parent issue.

**Comment by willtsai** [comment]
> Have added your project to https://github.com/cncf/contribute - @willtsai

@yaron2 @msfussell - can you please validate that this info is accurate, especially the CLA? And Dapr doesn't have a developer list/forum, correct?

*"The Distributed Application Runtime (Dapr) provides APIs that simplify microservice connectivity. Whether your communication pattern is service to service invocation or pub/sub messaging, Dapr helps you write resilient and secured microservices. By letting Dapr’s sidecar take care of the complex challenges such as service discovery, message broker integration, encryption, observability, and secret management, you can focus on business logic and keep your code simple."* - [Dapr - dapr.io](https://dapr.io/)

- **Project Repository:** https://github.com/dapr
- **Contributor Guide:** [dapr.io/contributing](https://docs.dapr.io/contributing/)
- **Chat:** [Dapr Discord Server](https://aka.ms/dapr-discord)
- **License:** [MIT](https://choosealicense.com/licenses/mit/)
- **Legal Requirements:** [CLA](https://cla.microsoft.com/)

Not applicable:
- **Developer List/Forum:** [ ][${PROJECT}-dev-list]

**Comment by msfussell** [comment]
This is what Dapr will adopt, not what it is now with MS. Licence is Apache 2.0 I suspect the CLA will need to be https://developercertificate.org/ .

**Comment by willtsai** [comment]
can check off this task `Have added your project to https://github.com/cncf/contribute`
https://github.com/cncf/contribute/pull/88

**Comment by willtsai** [comment]
@greenie-msft - you can check off this task too: `Understand the license allowlist`

In essence, the requirement is that any dependencies or libraries we have in Dapr need to either be under the Apache2.0 license or else under one of these licenses:
- BSD-2-Clause
- BSD-2-Clause-FreeBSD
- BSD-3-Clause
- MIT
- ISC
- Python-2.0
- PostgreSQL
- X11
- Zlib
- Google patent license for Golang (https://golang.org/PATENTS)

**Comment by msfussell** [comment]
Closing. https://github.com/cncf/toc/issues/738#issuecomment-1005268690 we're officially onboarded
